// Install REST Client extension to VSC if you don't have it.

GET http://localhost:8080/api/products HTTP/1.1

###

POST http://localhost:8080/api/customers  HTTP/1.1
Content-Type: application/json

{
    "first_name": "A",
    "last_name": "B",
    "street_address": "C",
    "city": "D",
    "postcode": "E",
    "phone": "F",
    "email": "testi",
    "password": "testi"
}

###

POST http://localhost:8080/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email": "ei@oo.fi",
    "password": "tämä"
}

###

POST http://localhost:8080/api/products  HTTP/1.1
Content-Type: application/json

{  
    "supplier_name": "Siivouspojat Oy",
    "product_name": "AAAAAAAAAAA",
    "product_description": "aaaa",
    "product_price": 5.50,
    "ends_at": null,
    "work_hours": 4,
    "is_available": true
}

###

GET http://localhost:8080/api/offer-requests?supplier= HTTP/1.1

###

POST http://localhost:8080/api/offer-requests  HTTP/1.1
Content-Type: application/json

{
    "apartment_type": "talo",
    "apartment_area": 38.5,
    "cleaning_frequency": "joka toinen päevä",
    "request_suppliers": "Petri",
    "optional_information": null,
    "first_name": "Juuso",
    "last_name": "Heinz",
    "street_address": ":)",
    "city": "Tre",
    "postcode": "23123",
    "phone": "33331111111",
    "email": "joo@joo.org"
}

###